retry parted/partprobe/blockdev forever
For corner cases where we would get device busy errors,
despite udev settle.

avoid endless loop when creating LVM partition:

Error: Can't have overlapping partitions.
i.e. first parted call succeeded creating partition, it failed only on
re-read.
Instead of blind until loop, check that partition is created.

rhbz#673017